
services:
  frontend:
    build:
      context: .
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: .
          target: /esc-frontend
          ignore:
            - node_modules