
services:
  frontend:
    build:
      context: .
    ports:
      - 8080:8080
    develop:
      watch:
        - action: sync
          path: .
          target: .
          ignore:
            - node_modules